work_dir: ./work_dir/train/pems07
model_saved_name: ./runs/pems07

gen_config_args:
  num_of_weeks: 0
  num_of_days: 0
  num_of_hours: 1
  num_for_predict: 12
  points_per_hour: 12
num_of_vertices: 883

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/PEMS07/train_data.npy
  label_path: ./data/PEMS07/train_label.pkl
  debug: False
test_feeder_args:
  data_path: ./data/PEMS07/val_data.npy
  label_path: ./data/PEMS07/val_label.pkl

# model
model: model.magcn.Model
model_args:
  in_channels: 1
  drop_out: 0
  adj_filename: data/PEMS07/PEMS07.csv
  id_filename: null
# training
device: [3]
batch_size: 32
test_batch_size: 64

#optim
base_lr: 0.001
step: [4]
num_epoch: 10
weight_decay: 0.01


